-- Major-aware chat: conversation page context + per-major advisor copy (DB-driven).
-- Suggested question chips are stored in English; extend suggested_questions_ar via SQL updates for Arabic labels if needed.

BEGIN;

ALTER TABLE chat_conversations
  ADD COLUMN IF NOT EXISTS context_major_id VARCHAR(100) NULL REFERENCES majors(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS major_chat_context (
  major_id VARCHAR(100) PRIMARY KEY REFERENCES majors(id) ON DELETE CASCADE,
  category VARCHAR(32) NOT NULL DEFAULT 'other',
  greeting_en TEXT NULL,
  greeting_ar TEXT NULL,
  suggested_questions_en JSONB NOT NULL DEFAULT '[]'::jsonb,
  suggested_questions_ar JSONB NOT NULL DEFAULT '[]'::jsonb,
  facts_en TEXT NULL,
  facts_ar TEXT NULL,
  engineering_program_key VARCHAR(80) NULL
);

CREATE INDEX IF NOT EXISTS idx_major_chat_context_category ON major_chat_context(category);

INSERT INTO major_chat_context (major_id, category, greeting_en, greeting_ar, suggested_questions_en, suggested_questions_ar, facts_en, facts_ar)
VALUES
  ('eng-mis', 'engineering',
   'Hello, I am your advisor for Management Information Systems. Ask me about anything we store for this programme (admission band, difficulty, competition notes, and descriptions).',
   $msg$أهلاً، أنا مساعدك لبرنامج نظم معلومات الإدارة. اسألني عن البيانات المخزّنة لهذا البرنامج.$msg$,
   '["Is this programme difficult?","What careers does MIS lead to?","Is it more technical or business-focused?","What is the stored admission band?"]'::jsonb,
   '["Is this programme difficult?","What careers does MIS lead to?","Is it more technical or business-focused?","What is the stored admission band?"]'::jsonb,
   'Facts in the catalogue are limited to what your team imported into engineering_programs for this major name.',
   'المعلومات تعتمد على ما تم استيراده في جدول برامج الهندسة لهذا الاسم.'),
  ('eng-cs', 'engineering',
   'Hello, I am your advisor for Computer Science. I only answer from your university database records for this programme.',
   $msg$أهلاً، أنا مساعدك لعلوم الحاسوب. بجاوب من سجلات قاعدة البيانات فقط.$msg$,
   '["Is this programme difficult?","Is it very math-heavy?","What does the catalogue say about competition?","What is the stored admission band?"]'::jsonb,
   '["Is this programme difficult?","Is it very math-heavy?","What does the catalogue say about competition?","What is the stored admission band?"]'::jsonb,
   NULL, NULL),
  ('eng-ee', 'engineering',
   'Hello, I am your advisor for Electrical Engineering. Ask using the programme name on this page so answers stay scoped.',
   $msg$أهلاً، أنا مساعدك للهندسة الكهربائية. اسأل ضمن اسم البرنامج المعروض.$msg$,
   '["Is this programme difficult?","What careers does EE usually point to in the catalogue?","Industrial vs scientific stream — what does the record say?","What is the stored admission band?"]'::jsonb,
   '["Is this programme difficult?","What careers does EE usually point to in the catalogue?","Industrial vs scientific stream — what does the record say?","What is the stored admission band?"]'::jsonb,
   NULL, NULL),
  ('eng-ce', 'engineering',
   'Hello, I am your advisor for Civil Engineering. I will keep answers focused on this programme unless you explicitly compare with another.',
   $msg$أهلاً، أنا مساعدك للهندسة المدنية. بظل الإجابات عن هذا البرنامج إلا إذا طلبت مقارنة صريحة.$msg$,
   '["Is this programme difficult?","What does the catalogue note about graduate pathways?","Is it more math-heavy?","What is the stored admission band?"]'::jsonb,
   '["Is this programme difficult?","What does the catalogue note about graduate pathways?","Is it more math-heavy?","What is the stored admission band?"]'::jsonb,
   NULL, NULL),
  ('eng-me', 'engineering',
   'Hello, I am your advisor for Mechanical Engineering.',
   $msg$أهلاً، أنا مساعدك للهندسة الميكانيكية.$msg$,
   '["Is this programme difficult?","Hands-on vs theory — what do the stored notes say?","What is competition like in the record?","What is the stored admission band?"]'::jsonb,
   '["Is this programme difficult?","Hands-on vs theory — what do the stored notes say?","What is competition like in the record?","What is the stored admission band?"]'::jsonb,
   NULL, NULL),
  ('eng-it', 'engineering',
   'Hello, I am your advisor for Information Technology.',
   $msg$أهلاً، أنا مساعدك لتقنية المعلومات.$msg$,
   '["Is this programme difficult?","Is it more programming or infrastructure in the catalogue?","What is the stored admission band?","What careers are hinted in the description?"]'::jsonb,
   '["Is this programme difficult?","Is it more programming or infrastructure in the catalogue?","What is the stored admission band?","What careers are hinted in the description?"]'::jsonb,
   NULL, NULL),
  ('eng-se', 'engineering',
   'Hello, I am your advisor for Software Engineering.',
   $msg$أهلاً، أنا مساعدك لهندسة البرمجيات.$msg$,
   '["Is this programme difficult?","How math-heavy is it in the stored metadata?","What is the stored admission band?","Compare workload vs Computer Science — using database rows only"]'::jsonb,
   '["Is this programme difficult?","How math-heavy is it in the stored metadata?","What is the stored admission band?","Compare workload vs Computer Science — using database rows only"]'::jsonb,
   NULL, NULL),
  ('arts-econ', 'arts',
   'Hello, I am your advisor for Economics. Programme detail rows for non-engineering majors are lighter; I will use what is stored here plus your profile when relevant.',
   $msg$أهلاً، أنا مساعدك للاقتصاد. بيانات غير الهندسة أخف؛ بستخدم المخزن هنا وملفك عند الحاجة.$msg$,
   '["Is this major more theory or applied?","What skills does the catalogue emphasise?","Is it a good fit if I like analysis and data?","How should I compare it with Business Administration?"]'::jsonb,
   '["Is this major more theory or applied?","What skills does the catalogue emphasise?","Is it a good fit if I like analysis and data?","How should I compare it with Business Administration?"]'::jsonb,
   'Economics majors often combine quantitative reasoning with social-science framing; check your official bulletin for the authoritative curriculum.',
   'الاقتصاد يجمع التفكير الكمي مع الإطار الاجتماعي؛ راجع النشرة الرسمية للمناهج.'),
  ('arts-psych', 'arts',
   'Hello, I am your advisor for Psychology.',
   $msg$أهلاً، أنا مساعدك لعلم النفس.$msg$,
   '["Is this major science-heavy or humanities-heavy?","What graduate paths are common?","Is clinical work part of the undergraduate story here?","Is it a good fit for me?"]'::jsonb,
   '["Is this major science-heavy or humanities-heavy?","What graduate paths are common?","Is clinical work part of the undergraduate story here?","Is it a good fit for me?"]'::jsonb,
   NULL, NULL),
  ('arts-bio', 'arts',
   'Hello, I am your advisor for Biology.',
   $msg$أهلاً، أنا مساعدك لعلم الأحياء.$msg$,
   '["Is this major lab-heavy in the official materials?","What careers does it prepare for?","How much chemistry is typically required?","Is it difficult?"]'::jsonb,
   '["Is this major lab-heavy in the official materials?","What careers does it prepare for?","How much chemistry is typically required?","Is it difficult?"]'::jsonb,
   NULL, NULL),
  ('bus-mgmt', 'business',
   'Hello, I am your advisor for Business Administration.',
   $msg$أهلاً، أنا مساعدك لإدارة الأعمال.$msg$,
   '["Is this major more theory or practical?","What job opportunities are highlighted?","Is it a good fit if I like leadership and organisations?","How does it compare with Economics here?"]'::jsonb,
   '["Is this major more theory or practical?","What job opportunities are highlighted?","Is it a good fit if I like leadership and organisations?","How does it compare with Economics here?"]'::jsonb,
   'Business programmes mix strategy, operations, and people skills; rely on your college handbook for course requirements.',
   'إدارة الأعمال تجمع الاستراتيجية والعمليات ومهارات التعامل؛ راجع دليل الكلية للمتطلبات.'),
  ('med-nursing', 'health',
   'Hello, I am your advisor for Nursing.',
   $msg$أهلاً، أنا مساعدك للتمريض.$msg$,
   '["Is this major more clinical or classroom in the official plan?","What does graduate licensing depend on locally?","Is it very demanding in hours?","Is it a good fit for me?"]'::jsonb,
   '["Is this major more clinical or classroom in the official plan?","What does graduate licensing depend on locally?","Is it very demanding in hours?","Is it a good fit for me?"]'::jsonb,
   'Nursing is tightly regulated; always confirm competencies and licensing rules with the faculty office.',
   'التمريض تنظيمي؛ تأكد من المتطلبات مع عمادة الكلية.'),
  ('law-legal', 'law',
   'Hello, I am your advisor for Law.',
   $msg$أهلاً، أنا مساعدك للقانون.$msg$,
   '["Is this major reading-heavy?","What practice paths are common after graduation?","Is it theory-first in the early years?","Is it a good fit if I like debate and writing?"]'::jsonb,
   '["Is this major reading-heavy?","What practice paths are common after graduation?","Is it theory-first in the early years?","Is it a good fit if I like debate and writing?"]'::jsonb,
   'Law study emphasises statutes, cases, and structured argument; verify bar / practice routes with your faculty.',
   'القانون يعتمد على النصوص والسوابق والحجة المنظمة؛ راجع مسار الممارسة مع الكلية.')
ON CONFLICT (major_id) DO UPDATE SET
  category = EXCLUDED.category,
  greeting_en = EXCLUDED.greeting_en,
  greeting_ar = EXCLUDED.greeting_ar,
  suggested_questions_en = EXCLUDED.suggested_questions_en,
  suggested_questions_ar = EXCLUDED.suggested_questions_ar,
  facts_en = COALESCE(EXCLUDED.facts_en, major_chat_context.facts_en),
  facts_ar = COALESCE(EXCLUDED.facts_ar, major_chat_context.facts_ar);

COMMIT;
