export const MAJORS_CATALOG = [
  { name: "Life Sciences", facultyName: "Faculty of Science", creditHours: 127, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "General science bachelor's degree." },
  { name: "Biotechnology", facultyName: "Faculty of Science", creditHours: 127, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Listed in the guide as Biology Biotechnology." },
  { name: "Mathematics", facultyName: "Faculty of Science", creditHours: 124, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Standard mathematics bachelor's degree." },
  { name: "Mathematics / Education", facultyName: "Faculty of Science", creditHours: 124, duration: "4 years", majorType: "Mixed (Scientific + Education)", minAdmission: "65%", notes: "Teacher-preparation route." },
  { name: "Mathematics and Data Science", facultyName: "Faculty of Science", creditHours: 135, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Current data-oriented mathematics track." },
  { name: "Mathematics / Statistics", facultyName: "Faculty of Science", creditHours: 124, duration: "4 years", majorType: "Mixed (Scientific)", minAdmission: "65%", notes: "Math major with statistics minor." },
  { name: "Mathematics / Insurance", facultyName: "Faculty of Science", creditHours: 121, duration: "4 years", majorType: "Mixed (Scientific + Business)", minAdmission: "65%", notes: "Math major with insurance minor." },
  { name: "Statistics", facultyName: "Faculty of Science", creditHours: 124, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Standalone statistics bachelor's degree." },
  { name: "Physics", facultyName: "Faculty of Science", creditHours: 128, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Standard physics bachelor's degree." },
  { name: "Physics / Education", facultyName: "Faculty of Science", creditHours: 125, duration: "4 years", majorType: "Mixed (Scientific + Education)", minAdmission: "65%", notes: "Teacher-preparation route." },
  { name: "Physics / Electronics", facultyName: "Faculty of Science", creditHours: 128, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Physics with electronics specialization." },
  { name: "Technology of Applied Physics", facultyName: "Faculty of Science", creditHours: 128, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Applied-physics technology track." },
  { name: "Chemistry", facultyName: "Faculty of Science", creditHours: 126, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Standard chemistry bachelor's degree." },
  { name: "Chemistry / Education", facultyName: "Faculty of Science", creditHours: 127, duration: "4 years", majorType: "Mixed (Scientific + Education)", minAdmission: "65%", notes: "Teacher-preparation route." },
  { name: "Applied Chemistry", facultyName: "Faculty of Science", creditHours: 125, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Applied chemistry bachelor's degree." },
  { name: "Applied Chemistry / Industrial Chemistry", facultyName: "Faculty of Science", creditHours: 127, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Applied chemistry with industrial chemistry minor." },
  { name: "Molecular Diagnostics Technologies", facultyName: "Faculty of Science", creditHours: 129, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Molecular diagnostics technologies." },
  { name: "Fiqh and Legislation", facultyName: "Faculty of Sharia Sciences", creditHours: 130, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "Shari'ah and legal studies track." },
  { name: "Usul al-Din", facultyName: "Faculty of Sharia Sciences", creditHours: 130, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "Foundations of religion track." },
  { name: "Usul al-Din / Arabic", facultyName: "Faculty of Sharia Sciences", creditHours: 131, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "Religion major with Arabic minor." },
  { name: "Islamic Banking", facultyName: "Faculty of Sharia Sciences", creditHours: 129, duration: "4 years", majorType: "Commercial / Business", minAdmission: "65%", notes: "Shari'ah-finance track." },
  { name: "Arabic Language and Literature", facultyName: "Faculty of Arts", creditHours: 125, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "" },
  { name: "English Language and Literature", facultyName: "Faculty of Arts", creditHours: 131, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "" },
  { name: "English / French", facultyName: "Faculty of Arts", creditHours: 131, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "English major with French minor." },
  { name: "English / American Studies", facultyName: "Faculty of Arts", creditHours: 134, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "English major with American Studies minor." },
  { name: "French Language", facultyName: "Faculty of Arts", creditHours: 126, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "" },
  { name: "French / English", facultyName: "Faculty of Arts", creditHours: 131, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "French major with English minor." },
  { name: "Tourism / Archaeological Site Management", facultyName: "Faculty of Arts", creditHours: 127, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "Tourism and archaeology route." },
  { name: "Tourism / Hotel Management", facultyName: "Faculty of Arts", creditHours: 127, duration: "4 years", majorType: "Commercial / Business", minAdmission: "65%", notes: "Tourism with hotel-management minor." },
  { name: "Tourism / Reservation & Travel", facultyName: "Faculty of Arts", creditHours: 127, duration: "4 years", majorType: "Commercial / Business", minAdmission: "65%", notes: "Tourism with travel-services minor." },
  { name: "History", facultyName: "Faculty of Arts", creditHours: 127, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "" },
  { name: "Arabic / Hebrew", facultyName: "Faculty of Arts", creditHours: 128, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "Arabic major with Hebrew minor." },
  { name: "English / Hebrew", facultyName: "Faculty of Arts", creditHours: 131, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "English major with Hebrew minor." },
  { name: "Arabic / Education", facultyName: "Faculty of Educational Sciences and Teacher Training", creditHours: 128, duration: "4 years", majorType: "Mixed (Humanities + Education)", minAdmission: "65%", notes: "Teacher-preparation route." },
  { name: "History / Education", facultyName: "Faculty of Educational Sciences and Teacher Training", creditHours: 128, duration: "4 years", majorType: "Mixed (Humanities + Education)", minAdmission: "65%", notes: "Teacher-preparation route." },
  { name: "English / Education", facultyName: "Faculty of Educational Sciences and Teacher Training", creditHours: 131, duration: "4 years", majorType: "Mixed (Humanities + Education)", minAdmission: "65%", notes: "Teacher-preparation route." },
  { name: "English / Translation", facultyName: "Faculty of Arts", creditHours: 131, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "English major with translation minor." },
  { name: "Psychology / Psychological Counseling", facultyName: "Faculty of Arts", creditHours: 127, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "Psychology with counseling minor." },
  { name: "Geography", facultyName: "Faculty of Arts", creditHours: 127, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "" },
  { name: "Geography / Geomatics", facultyName: "Faculty of Arts", creditHours: 129, duration: "4 years", majorType: "Mixed (Humanities + Scientific)", minAdmission: "65%", notes: "Geography with geomatics minor." },
  { name: "Social Work", facultyName: "Faculty of Arts", creditHours: 131, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "" },
  { name: "Kindergartens / Early Childhood Education", facultyName: "Faculty of Educational Sciences and Teacher Training", creditHours: 127, duration: "4 years", majorType: "Mixed (Education / Scientific)", minAdmission: "65%", notes: "" },
  { name: "Physical Education", facultyName: "Faculty of Physical Education and Sports Sciences", creditHours: 131, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "" },
  { name: "Inclusive and Special Education", facultyName: "Faculty of Educational Sciences and Teacher Training", creditHours: 128, duration: "4 years", majorType: "Mixed (Education)", minAdmission: "65%", notes: "" },
  { name: "Civil Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Engineering threshold. Covers structural, geotechnical, and infrastructure design." },
  { name: "Surveying and Geomatics Engineering", facultyName: "Faculty of Engineering", creditHours: 159, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Also called Geomatics Engineering on the English website." },
  { name: "Architectural Engineering", facultyName: "Faculty of Engineering", creditHours: 165, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Architecture-focused engineering track." },
  { name: "Building Engineering", facultyName: "Faculty of Engineering", creditHours: 165, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Building systems and construction engineering." },
  { name: "Planning Engineering and City Technology", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Urban-planning engineering track." },
  { name: "Mechanical Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Standard mechanical engineering track." },
  { name: "Chemical Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Standard chemical engineering track." },
  { name: "Industrial Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Standard industrial engineering track." },
  { name: "Computer Engineering", facultyName: "Faculty of Engineering", creditHours: 163, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Hardware and software engineering." },
  { name: "Electrical Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Power and electronics engineering." },
  { name: "Networks and Intelligent Systems Engineering", facultyName: "Faculty of Engineering", creditHours: 161, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Also called Telecommunication Engineering on the English website." },
  { name: "Mechatronics Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Combines mechanical, electrical, and computing systems." },
  { name: "Energy and Environmental Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Energy systems and environmental impact." },
  { name: "Biomedical Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Medical devices and health technology engineering." },
  { name: "Materials Science and Engineering", facultyName: "Faculty of Engineering", creditHours: 162, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Engineering materials track." },
  { name: "Safety Engineering", facultyName: "Faculty of Engineering", creditHours: 161, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "75%", notes: "Workplace and industrial safety engineering." },
  { name: "Computer Science", facultyName: "Faculty of Information Technology & Artificial Intelligence", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Core CS theory and programming." },
  { name: "Management Information Systems", facultyName: "Faculty of Information Technology & Artificial Intelligence", creditHours: 124, duration: "4 years", majorType: "Mixed (Scientific + Business + Literary)", minAdmission: "65%", notes: "Combines IT and business management. Accepts scientific, literary, and business streams." },
  { name: "Information Technology", facultyName: "Faculty of Information Technology & Artificial Intelligence", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Applied IT systems and networks." },
  { name: "Software Engineering", facultyName: "Faculty of Information Technology & Artificial Intelligence", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Software development lifecycle and engineering." },
  { name: "Cybersecurity", facultyName: "Faculty of Information Technology & Artificial Intelligence", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Network and information security." },
  { name: "AI and Data Science", facultyName: "Faculty of Information Technology & Artificial Intelligence", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Artificial intelligence and data science. New program." },
  { name: "Doctor of Medicine", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 230, duration: "6 years", majorType: "Practical / Scientific", minAdmission: "90%", notes: "MD degree. Highest admission threshold." },
  { name: "Optometry", facultyName: "Faculty of Optometry", creditHours: 139, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Medical Laboratory Sciences", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 138, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Audiology and Speech Sciences", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 134, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Physiotherapy", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 140, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Cardiac Perfusion Technology", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 134, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Midwifery", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 134, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Medical Imaging", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 134, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Anesthesia and Resuscitation", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 134, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Clinical Nutrition", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 134, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Health Information Management", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 130, duration: "4 years", majorType: "Mixed (Scientific + Business)", minAdmission: "70%", notes: "" },
  { name: "Pharmacy", facultyName: "Faculty of Pharmacy", creditHours: 175, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "80%", notes: "Standard pharmacy bachelor's degree." },
  { name: "PharmD", facultyName: "Faculty of Pharmacy", creditHours: 175, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "80%", notes: "Doctor of Pharmacy professional degree." },
  { name: "Nursing", facultyName: "Faculty of Nursing", creditHours: 136, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Doctor of Dental Surgery", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 210, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "85%", notes: "DDS degree." },
  { name: "Dental Laboratory Technology", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 130, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Dental Hygiene", facultyName: "Faculty of Medicine and Health Sciences", creditHours: 128, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Business Administration", facultyName: "Faculty of Economics and Social Sciences", creditHours: 132, duration: "4 years", majorType: "Commercial / Business", minAdmission: "65%", notes: "" },
  { name: "Accounting", facultyName: "Faculty of Economics and Social Sciences", creditHours: 132, duration: "4 years", majorType: "Commercial / Business", minAdmission: "65%", notes: "" },
  { name: "Finance and Banking", facultyName: "Faculty of Economics and Social Sciences", creditHours: 132, duration: "4 years", majorType: "Commercial / Business", minAdmission: "65%", notes: "" },
  { name: "Marketing", facultyName: "Faculty of Economics and Social Sciences", creditHours: 132, duration: "4 years", majorType: "Commercial / Business", minAdmission: "65%", notes: "" },
  { name: "Public Relations and Advertising", facultyName: "Faculty of Economics and Social Sciences", creditHours: 132, duration: "4 years", majorType: "Mixed (Humanities + Business)", minAdmission: "65%", notes: "" },
  { name: "Journalism and Media", facultyName: "Faculty of Economics and Social Sciences", creditHours: 132, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "" },
  { name: "E-Commerce", facultyName: "Faculty of Economics and Social Sciences", creditHours: 132, duration: "4 years", majorType: "Mixed (Scientific + Business)", minAdmission: "65%", notes: "" },
  { name: "Economics", facultyName: "Faculty of Economics and Social Sciences", creditHours: 132, duration: "4 years", majorType: "Commercial / Business", minAdmission: "65%", notes: "" },
  { name: "Law", facultyName: "Faculty of Law", creditHours: 138, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "75%", notes: "Law degree with 75% threshold." },
  { name: "Political Sciences", facultyName: "Faculty of Law", creditHours: 132, duration: "4 years", majorType: "Literary / Humanities", minAdmission: "65%", notes: "" },
  { name: "Visual Arts", facultyName: "Faculty of Fine Arts", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Requires passing faculty aptitude exam." },
  { name: "Music", facultyName: "Faculty of Fine Arts", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Requires passing faculty aptitude exam." },
  { name: "Interior Design", facultyName: "Faculty of Fine Arts", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "Requires passing faculty aptitude exam." },
  { name: "Veterinary Medicine", facultyName: "Faculty of Veterinary Medicine", creditHours: 185, duration: "5 years", majorType: "Practical / Scientific", minAdmission: "70%", notes: "" },
  { name: "Animal Production and Veterinary Sciences", facultyName: "Faculty of Veterinary Medicine", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "" },
  { name: "Plant Production and Protection", facultyName: "Faculty of Agriculture", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "" },
  { name: "Nutrition and Food Technology", facultyName: "Faculty of Agriculture", creditHours: 132, duration: "4 years", majorType: "Practical / Scientific", minAdmission: "65%", notes: "" },
].map((major, idx) => ({
  ...major,
  id: `major-${idx + 1}`,
  slug: (major.name || '')
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, ''),
}));
